### ISSUE TITLE
config/database.yml uses sqlite instead of looking for a mysql in VCAP_SERVICES

### ISSUE THREAD

**Issue by mattly** [appfog/af-ruby-rails#1]
This is not good, we should be looking for the bound database and using that instead.

**Comment by mattly** [comment]
Also, it's helpful to have examples of how to do this.

**Comment by lhitchon** [comment]
vcap should automatically rewrite the database.yml config file if there is a bound service.
And this works when I deploy the app to my generic cf installation (no AppFog modifications).
So it looks like an AppFog specific modification or config change

**Comment by skierkowski** [comment]
Here is your solution:

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  host: <%= JSON.parse( ENV['VCAP_SERVICES'] )['mysql-5.1'].first['credentials']['hostname'] rescue 'localhost' %>
  port: <%= JSON.parse( ENV['VCAP_SERVICES'] )['mysql-5.1'].first['credentials']['port'] rescue 3306 %>
  database:  <%= JSON.parse( ENV['VCAP_SERVICES'] )['mysql-5.1'].first['credentials']['name'] rescue '' %>
  username: <%= JSON.parse( ENV['VCAP_SERVICES'] )['mysql-5.1'].first['credentials']['username'] rescue '' %>
  password: <%= JSON.parse( ENV['VCAP_SERVICES'] )['mysql-5.1'].first['credentials']['password'] rescue '' %>

**Comment by okalex** [comment]
Phew. Thanks for resolving this in a timely manner. :+1:

**Comment by mattly** [comment]
Someone's gotta close it

**Comment by stephas** [comment]
This took me back. Glad it's solved. 🦄
